import 'package:flutter/material.dart';

// Common TextTheme
const TextTheme textTheme = TextTheme(
  displayLarge: TextStyle(fontSize: 96, fontWeight: FontWeight.bold),
  displayMedium: TextStyle(fontSize: 60, fontWeight: FontWeight.bold),
  displaySmall: TextStyle(fontSize: 48, fontWeight: FontWeight.bold),
  headlineLarge: TextStyle(fontSize: 34, fontWeight: FontWeight.bold),
  headlineMedium: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
  headlineSmall: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
  bodyLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.normal),
  bodyMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.normal),
  bodySmall: TextStyle(fontSize: 12, fontWeight: FontWeight.normal),
  labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
  labelMedium: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
  labelSmall: TextStyle(fontSize: 10, fontWeight: FontWeight.bold),
);

// Light theme with custom colors and TextTheme
ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff8f4c38),
    surfaceTint: Color(0xff8f4c38),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffffdbd1),
    onPrimaryContainer: Color(0xff3a0b01),
    secondary: Color(0xff77574e),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffdbd1),
    onSecondaryContainer: Color(0xff2c150f),
    tertiary: Color(0xff6c5d2f),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xfff5e1a7),
    onTertiaryContainer: Color(0xff231b00),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffff8f6),
    onSurface: Color(0xff231917),
    onSurfaceVariant: Color(0xff53433f),
    outline: Color(0xff85736e),
    outlineVariant: Color(0xffd8c2bc),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff392e2b),
    inversePrimary: Color(0xffffb5a0),
    primaryFixed: Color(0xffffdbd1),
    onPrimaryFixed: Color(0xff3a0b01),
    primaryFixedDim: Color(0xffffb5a0),
    onPrimaryFixedVariant: Color(0xff723523),
    secondaryFixed: Color(0xffffdbd1),
    onSecondaryFixed: Color(0xff2c150f),
    secondaryFixedDim: Color(0xffe7bdb2),
    onSecondaryFixedVariant: Color(0xff5d4037),
    tertiaryFixed: Color(0xfff5e1a7),
    onTertiaryFixed: Color(0xff231b00),
    tertiaryFixedDim: Color(0xffd8c58d),
    onTertiaryFixedVariant: Color(0xff534619),
    surfaceDim: Color(0xffe8d6d2),
    surfaceBright: Color(0xfffff8f6),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffff1ed),
    surfaceContainer: Color(0xfffceae5),
    surfaceContainerHigh: Color(0xfff7e4e0),
    surfaceContainerHighest: Color(0xfff1dfda),
  ),
  textTheme: textTheme,
  useMaterial3: true,
);

// Dark theme with custom colors and TextTheme
ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffffb5a0),
    surfaceTint: Color(0xffffb5a0),
    onPrimary: Color(0xff561f0f),
    primaryContainer: Color(0xff723523),
    onPrimaryContainer: Color(0xffffdbd1),
    secondary: Color(0xffe7bdb2),
    onSecondary: Color(0xff442a22),
    secondaryContainer: Color(0xff5d4037),
    onSecondaryContainer: Color(0xffffdbd1),
    tertiary: Color(0xffd8c58d),
    onTertiary: Color(0xff3b2f05),
    tertiaryContainer: Color(0xff534619),
    onTertiaryContainer: Color(0xfff5e1a7),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff1a110f),
    onSurface: Color(0xfff1dfda),
    onSurfaceVariant: Color(0xffd8c2bc),
    outline: Color(0xffa08c87),
    outlineVariant: Color(0xff53433f),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xfff1dfda),
    inversePrimary: Color(0xff8f4c38),
    primaryFixed: Color(0xffffdbd1),
    onPrimaryFixed: Color(0xff3a0b01),
    primaryFixedDim: Color(0xffffb5a0),
    onPrimaryFixedVariant: Color(0xff723523),
    secondaryFixed: Color(0xffffdbd1),
    onSecondaryFixed: Color(0xff2c150f),
    secondaryFixedDim: Color(0xffe7bdb2),
    onSecondaryFixedVariant: Color(0xff5d4037),
    tertiaryFixed: Color(0xfff5e1a7),
    onTertiaryFixed: Color(0xff231b00),
    tertiaryFixedDim: Color(0xffd8c58d),
    onTertiaryFixedVariant: Color(0xff534619),
    surfaceDim: Color(0xff1a110f),
    surfaceBright: Color(0xff423734),
    surfaceContainerLowest: Color(0xff140c0a),
    surfaceContainerLow: Color(0xff231917),
    surfaceContainer: Color(0xff271d1b),
    surfaceContainerHigh: Color(0xff322825),
    surfaceContainerHighest: Color(0xff3d322f),
  ),
  textTheme: textTheme,
  useMaterial3: true,
);
